### ISSUE TITLE
easier installation on windows?

### ISSUE THREAD

**Issue by ifmihai** [astrorigin/pyswisseph#4] opened 2015-04-29 17:53 UTC
I have windows 7 64-bit
I installed anaconda, python 2.7 32-bit

I tried to install pyswisseph, as it's a default package for me,
but I bumped into errors, then i read about cmake road

I tried to find some already build version on binstar.org, nothing

I'm no expert, and when I read the info, about going into cmake, mingw visual studio, \\ or \\\,
i'm confused at least, minimal info.

Wouldn't it be better to have a build for windows? on binstar.org also?

**Comment by androidanit** [comment] 2015-10-14 13:53
Astrorigin,

Actually today I followed simple path to install under windows + python27 but it seems that there is a BUG which causes the error.

1. Installed VC++ compiler for python 2.7
Link : http://aka.ms/vcpython27
2. Then fired - pip install pyswisseph 
It ran into errors ! The referenced lines were from swephelp\swhgeo.c pointing to codeblock which is not meant for WIN32. That is  -
#ifndef WIN32
    char *saveptr;
    ptr = strtok_r(buf, ":", &saveptr);
#else
    ptr = strtok(buf, ":");
3. So applied quick and dirty patch in swephelp\swhgeo.c -
#ifndef WIN32
#define WIN32      1
#endif /* Hey I am WIN32 */
4. Then installed from source
pip install <path of pyswisseph local copy>
5. It worked!!!

I am not expert, so could get to root cause.
If you can confirm and fix this BUG, it will save days for windows users :-)

Thanks

**Comment by astrorigin** [comment] 2017-11-17 16:56
Got it. That should be fixed now. Hopefully.

**Closed by astrorigin** 2017-11-17 16:56 UTC
Labels: enhancement
